# Generated by Django 4.2.3 on 2023-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')]),
        ),
    ]
