# Generated by Django 4.2.3 on 2023-08-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0008_customuser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
