# Generated by Django 4.2.3 on 2023-08-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0011_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
