# Generated by Django 4.2.3 on 2023-08-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0013_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.SmallIntegerField(choices=[('male', 1), ('female', 2), ('other', 3)], null=True),
        ),
    ]
