# Generated by Django 4.2.3 on 2023-08-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0017_remove_user_created_at_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
